'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

/**
 * UserProvider / useUserId (Story 2.7).
 *
 * The anonymous UUID v4 is generated by the inline `<head>` script in
 * `app/layout.tsx` BEFORE React hydrates and persisted to localStorage
 * under the key `ai-quiz.user.id`. This provider reads it on mount.
 *
 * No fallback generation happens here — if the script failed (SSR-disabled,
 * blocking JS, denied localStorage), the page must render the empty UUID
 * rather than synthesize a fresh one, otherwise every render would create
 * a new identity and rate-limit / ownership would silently break.
 */
const STORAGE_KEY = 'ai-quiz.user.id';
const EMPTY = '';

const UserContext = createContext<string>(EMPTY);

interface UserProviderProps {
  readonly children: React.ReactNode;
}

export function UserProvider({ children }: UserProviderProps): React.JSX.Element {
  const [userId, setUserId] = useState<string>(EMPTY);

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw && raw.length > 0) {
        setUserId(raw);
      }
    } catch {
      /* ignore storage failures; user id stays empty */
    }
  }, []);

  const value = useMemo(() => userId, [userId]);

  return <UserContext.Provider value={value}>{children}</UserContext.Provider>;
}

export function useUserId(): string {
  return useContext(UserContext);
}
